spring:
  datasource:
    hikari:
      maximum-pool-size: 100 #커넥션 풀 갯수 설정
  profiles:
    include: oauth
  jpa:
#    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false # 쿼리를 가독성있게 바꿔줌
  session:
    store-type: jdbc
  # 이미지 파일 용량 제한 수정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace