spring:
  datasource:
    hikari:
      maximum-pool-size: 50 #커넥션 풀 갯수 설정
  profiles:
    include: oauth
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc
  # 이미지 파일 용량 제한 수정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB