on:
  pull_request:
    branches:
      - dev-fe
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: 'dev-fe'
          
      - name: pwd && ls -al
        run: ls -al
        
      - name: Install dependencies
        run: npm install
        working-directory: "./client"
        
      - name: Generate Environment Variables File
        run: |
          echo "REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL" >> .env
          echo "REACT_APP_KAKAO_AUTH_URL=$REACT_APP_KAKAO_AUTH_URL" >> .env
          echo "REACT_APP_CRYPTION_SALT=$REACT_APP_CRYPTION_SALT" >> .env
        env: 
          REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
          REACT_APP_KAKAO_AUTH_URL: ${{ secrets.REACT_APP_KAKAO_AUTH_URL }}
          REACT_APP_CRYPTION_SALT: ${{ secrets.REACT_APP_CRYPTION_SALT }}
        working-directory: "./client"

      - name: react build
        run: npm run build
        env:
          CI: false
        working-directory: "./client"

      - name: SHOW AWS CLI VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws --version
          
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            ./client/build s3://oneyearfourcut-front \
            --delete
